trydjango1-11/src/menus/urls.py
from django.conf.urls import url


from .views import (
    ItemListView,
    ItemDetailView,
    ItemUpdateView,
    ItemCreateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    
]

trydjango1-11/src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^password-reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^password-reset/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name = 'about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name = 'contact.html'), name='contact'), #(?P<id>\d+)/ regex for id
    url(r'^password-reset/complete/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

trydjango1-11/src/menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import RestaurantLocation
# Create your models here.

class Item(models.Model):
    #associations
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(RestaurantLocation)

    #items
    name        = models.CharField(max_length=120)
    contents    = models.TextField(help_text='Separate each item by comma')
    excludes    = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    public      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

trydjango1-11/src/menus/forms.py
from django import forms

from restaurants.models import RestaurantLocation

from .models import Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public',
        ]

    def __init__(self, user=None, *args, **kwargs):
        #print('kwargs:',kwargs.pop('user'))
        print(user)
        #print(kwargs.pop('instance'))
        super(ItemForm, self).__init__(*args,**kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user) #.exclude(item__isnull=False) - This exclude is used to remove restaurants which are already used as relation !

trydjango1-11/src/menus/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Item
from .forms import ItemForm

class HomeView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'home.html', {})

        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()] 
        qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by('-updated')[:3]


        return render(request, 'menus/home-feed.html', {'object_list': qs})

class ItemListView(LoginRequiredMixin, ListView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemDetailView(LoginRequiredMixin, DetailView):

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(CreateView,LoginRequiredMixin):
    template_name = 'form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView,self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Item'
        return context

class ItemUpdateView(UpdateView,LoginRequiredMixin):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView,self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

trydjango1-11/src/menus/templates/menus/detail-update.html
{% extends "base.html" %}
{% block head_title %}Menu Items | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }}</h1>
<p>Location: {{ form.instance.restaurant.name }}</p>
{% if form.instance.contents %}
Contents
<ul>
    {% for item in form.instance.get_contents %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if form.instance.excludes %}
Excludes
<ul>
    {% for item in form.instance.get_excludes %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
{% endif %}

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

trydjango1-11/src/menus/templates/menus/home-feed.html
{% extends 'base.html' %}

{% block content %}
<div class='row'>
<div class='col-sm-6 text-center col-sm-offset-3'>
        <h1>User Following Feed</h1>
{% for obj in object_list %}
  
    
        <div class='thumbnail'> 
            <h4><a href="{% url 'profile:detail' username=obj.user.username %}">{{ obj.user.username }}</a></h4>
            <h4>{{ obj.name }}</h4>
            <p>
                <a href="{% url 'profile:detail' username=obj.user.username %}?q={{ obj.restaurant.title }}">{{ obj.restaurant.title }}</a>
                | <a href="{% url 'profile:detail' username=obj.user.username %}?q={{ obj.restaurant.location }}">{{ obj.restaurant.location }}</a>
                | <a href="{% url 'profile:detail' username=obj.user.username %}?q={{ obj.restaurant.category }}">{{ obj.restaurant.category }}</a>
            </p>
            <p>
                <b>{{ obj.name }}</b> with :
                {% for ing in obj.get_contents %}
                    <a href='{% url 'profile:detail' username=obj.user.username %}?q={{ ing }}'>
                        {{ ing }}
                    </a>
                {% endfor %}

            </p>
        </div>
    
    
        
{% endfor %}
</div>
</div>
{% endblock content %}

trydjango1-11/src/menus/templates/menus/item_list.html
{% extends "base.html" %}
{% block head_title %}Menu Items | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Menu Items <small><a href="{% url 'menus:create' %}">Add</a></small></h1>

<ul>
{% for obj in object_list %}
    <li> 
        <a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a>
    </li>
        {% if obj.contents %} 

        Contents
        <ul>
            {% for item in obj.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if obj.excludes %}
        Excludes
        <ul>
            {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        {% empty %}
        <li>
            <small>
                <a href="{% url 'menus:create' %}">Add Menu Item</a>
            </small>
        </li>
        
{% endfor %}
</ul>
{% endblock %}